'use strict';

let snapshot={decision:'UNKNOWN',freshness:'STALE',ageMinutes:null,nextChange:'—',sourceId:'NONE',sourceRole:'UNAVAILABLE',research:{tanitaScoreEffect:0,v19_2ScoreEffect:0}};
const allowedDecision=new Set(['ACT','CAUTION','HOLD','UNKNOWN']);
const allowedFreshness=new Set(['LIVE','DELAYED','LAST_GOOD','STALE']);
const acceptSnapshot=data=>{if(!data||data.schema!=='neborythm_mobile_snapshot_v1'||!allowedDecision.has(data.decision)||!allowedFreshness.has(data.freshness)||data.research?.tanita_score_effect!==0||data.research?.v19_2_score_effect!==0)throw new Error('invalid mobile snapshot');snapshot={decision:data.decision,freshness:data.freshness,ageMinutes:Number.isFinite(data.age_minutes)?data.age_minutes:null,nextChange:data.next_change||'—',sourceId:data.source_id||'UNKNOWN',sourceRole:data.source_role||'UNDECLARED',research:{tanitaScoreEffect:0,v19_2ScoreEffect:0}};};
const copy={
  uk:{minutes:'хв',largeText:'Великий текст',language:'Мова',nav:{today:'Сьогодні',timeline:'Час',sky:'Небо',jyotish:'Jyotish',you:'Ви'},today:{title:'Сьогодні',mode:'Підготуватися',decision:'Дійте обережно',reason:'Сигнали розходяться: поточний фон напружений, а традиційний календарний шар змішаний.',suitable:'Доречно',suitableAction:'Завершувати та перевіряти',defer:'Краще відкласти',deferAction:'Нові ризикові кроки',why:'Чому?',next:'Наступна зміна',layers:'Шари контексту',explain:'Observed context і один агрегований Jyotish-компонент. Tanita та v19.2: score effect 0.',sources:[['Космічна погода','Kp та сонячний вітер','OBSERVED','враховано'],['Події неба','Місяць, планети, затемнення','INFO','не змінює'],['Jyotish','Ведичний календар дня','TRADITIONAL','вже враховано']]},timeline:{title:'Найближчі години',slots:[['09:00','hold','Зачекати','Оперативна пауза'],['12:00','','Підготуватися','Сигнали ще розходяться'],['15:00','review','Переглянути','Новий прогнозний зріз'],['18:00','','Обережне вікно','Не гарантія результату']],days:'27 днів',note:'Raw-контекст, оперативний стан і reference показуються окремо.'},sky:{title:'Небо',intro:'Фізичні події та розрахований контекст. Кожна картка показує роль в оцінці.',cards:[['OBSERVED · 4 хв','Kp 3.2','NOAA · враховано'],['CALCULATED','Місяць 96%','інформаційно'],['VISIBLE · 04:43','6 планет','score effect 0'],['EVENT','Затемнення','score effect 0']],note:'Зелена доступність джерела не означає сприятливий день.'},jyotish:{intro:'Ведичний календар і персональний ритм. Не окремий другий прогноз.',rahunote:'Локальний календарний інтервал; уже входить в один компонент P.'},you:{title:'Моя справа',intro:'Вибір змінює пояснення й пошук вікна, але не головну оцінку.',choices:{focus:'Фокус-робота',meeting:'Зустріч',travel:'Подорож',rest:'Відпочинок'},result:'Результат не гарантовано.',after:'Після справи',outcomes:['Краще','Як очікував','Змішано'],local:'Запис локальний. Замало даних для персонального патерну.',export:'Експортувати JSON',delete:'Видалити локальні дані',birth:'Дані народження в цьому MVP не збираються.'}},
  en:{minutes:'min',largeText:'Large text',language:'Language',nav:{today:'Today',timeline:'Time',sky:'Sky',jyotish:'Jyotish',you:'You'},today:{title:'Today',mode:'Prepare',decision:'Proceed carefully',reason:'Signals diverge: the current environment is tense while the traditional timing layer is mixed.',suitable:'Good for',suitableAction:'Finish and review',defer:'Better to defer',deferAction:'New high-risk steps',why:'Why?',next:'Next change',layers:'Context layers',explain:'Observed context and one aggregated Jyotish component. Tanita and v19.2: score effect 0.',sources:[['Space weather','Kp and solar wind','OBSERVED','included'],['Sky events','Moon, planets, eclipses','INFO','no score change'],['Jyotish','Traditional daily timing','TRADITIONAL','already included']]},timeline:{title:'Next hours',slots:[['09:00','hold','Hold','Operational pause'],['12:00','','Prepare','Signals still diverge'],['15:00','review','Review','New forecast snapshot'],['18:00','','Cautious window','Not a result guarantee']],days:'27 days',note:'Raw context, operational state, and reference are shown separately.'},sky:{title:'Sky',intro:'Physical events and calculated context. Every card states its role in the assessment.',cards:[['OBSERVED · 4 min','Kp 3.2','NOAA · included'],['CALCULATED','Moon 96%','informational'],['VISIBLE · 04:43','6 planets','score effect 0'],['EVENT','Eclipse','score effect 0']],note:'A green source-availability state does not mean a favourable day.'},jyotish:{intro:'Traditional Indian timing and personal rhythm. It is not a second competing forecast.',rahunote:'Local traditional interval; already included in the single P component.'},you:{title:'My activity',intro:'Your choice changes the explanation and window search, not the main assessment.',choices:{focus:'Focus work',meeting:'Meeting',travel:'Travel',rest:'Rest'},result:'Outcome is not guaranteed.',after:'After the activity',outcomes:['Better','As expected','Mixed'],local:'Saved locally. Not enough data for a personal pattern yet.',export:'Export JSON',delete:'Delete local data',birth:'Birth data is not collected in this MVP.'}},
  es:{minutes:'min',largeText:'Texto grande',language:'Idioma',nav:{today:'Hoy',timeline:'Tiempo',sky:'Cielo',jyotish:'Jyotish',you:'Tú'},today:{title:'Hoy',mode:'Preparar',decision:'Avanza con cuidado',reason:'Las señales divergen: el entorno actual está tenso y la capa tradicional de tiempo es mixta.',suitable:'Adecuado para',suitableAction:'Terminar y revisar',defer:'Mejor aplazar',deferAction:'Nuevos pasos de alto riesgo',why:'¿Por qué?',next:'Próximo cambio',layers:'Capas de contexto',explain:'Contexto observado y un componente Jyotish agregado. Tanita y v19.2: efecto en la puntuación 0.',sources:[['Clima espacial','Kp y viento solar','OBSERVED','incluido'],['Eventos del cielo','Luna, planetas y eclipses','INFO','sin cambio'],['Jyotish','Calendario tradicional del día','TRADITIONAL','ya incluido']]},timeline:{title:'Próximas horas',slots:[['09:00','hold','Espera','Pausa operativa'],['12:00','','Preparar','Las señales aún divergen'],['15:00','review','Revisar','Nueva actualización del pronóstico'],['18:00','','Ventana cautelosa','No garantiza un resultado']],days:'27 días',note:'El contexto raw, el estado operativo y la referencia se muestran por separado.'},sky:{title:'Cielo',intro:'Eventos físicos y contexto calculado. Cada tarjeta muestra su función en la evaluación.',cards:[['OBSERVED · 4 min','Kp 3.2','NOAA · incluido'],['CALCULATED','Luna 96%','informativo'],['VISIBLE · 04:43','6 planetas','efecto 0'],['EVENT','Eclipse','efecto 0']],note:'Que una fuente esté disponible en verde no significa que el día sea favorable.'},jyotish:{intro:'Tiempo tradicional de la India y ritmo personal. No es un segundo pronóstico que compita.',rahunote:'Intervalo tradicional local; ya está incluido en el único componente P.'},you:{title:'Mi actividad',intro:'Tu elección cambia la explicación y la búsqueda de ventanas, no la evaluación principal.',choices:{focus:'Trabajo enfocado',meeting:'Reunión',travel:'Viaje',rest:'Descanso'},result:'El resultado no está garantizado.',after:'Después de la actividad',outcomes:['Mejor','Como esperaba','Mixto'],local:'Guardado localmente. Aún no hay suficientes datos para un patrón personal.',export:'Exportar JSON',delete:'Borrar datos locales',birth:'Los datos de nacimiento no se recopilan en este MVP.'}}
};
const content=document.getElementById('content');
const locale=document.getElementById('locale');
const storageKey='neborythm.local.v1';
const offlineMode=new URLSearchParams(location.search).get('offline')==='1'||!navigator.onLine;
const safe=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let route='today';
let timelineRange='24h';
let localState={locale:'uk',largeText:false,activity:'focus',checkins:[],alerts:{kp:true,decision:false,threshold:5,quietStart:'22:00',quietEnd:'07:00'}};
try{localState={...localState,...JSON.parse(localStorage.getItem(storageKey)||'{}')};}catch{localStorage.removeItem(storageKey);}
localState.alerts={kp:true,decision:false,threshold:5,quietStart:'22:00',quietEnd:'07:00',...(localState.alerts||{})};
locale.value=['uk','en','es'].includes(localState.locale)?localState.locale:'uk';
document.documentElement.classList.toggle('large-text',Boolean(localState.largeText));
document.getElementById('mode').setAttribute('aria-pressed',String(Boolean(localState.largeText)));
let activity=localState.activity;
const persist=()=>localStorage.setItem(storageKey,JSON.stringify({...localState,locale:locale.value,largeText:document.documentElement.classList.contains('large-text'),activity}));
const downloadLocalData=()=>{const blob=new Blob([JSON.stringify({...localState,locale:locale.value,activity,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='neborythm-local-data.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),0);};

function todayView(t){const d=t.today;const freshness=offlineMode?'LAST_GOOD':snapshot.freshness;const age=offlineMode?12:snapshot.ageMinutes;const ageText=age===null?'—':`${age} ${t.minutes}`;const demo=snapshot.sourceRole==='DEMO_NOT_PRODUCTION'?'<div class="demo-notice" role="status"><strong>DEMO DATA</strong><span>Product shell · not a live forecast</span></div>':'';return `<div class="section-head"><h1>${d.title}</h1><span class="fresh ${offlineMode||freshness!=='LIVE'?'stale':''}">● ${freshness} · ${ageText}</span></div>${demo}${offlineMode?'<div class="offline-notice" role="status">Offline · saved snapshot · not live</div>':''}<article class="hero" data-decision="${snapshot.decision}" aria-label="${safe(d.decision)}. ${safe(d.reason)}. ${safe(d.next)} ${snapshot.nextChange}"><div class="eyebrow">${d.mode}</div><div class="decision">${d.decision}</div><p class="muted">${safe(d.reason)}</p><div class="action-grid"><div class="panel"><small>${d.suitable}</small><strong>${d.suitableAction}</strong></div><div class="panel"><small>${d.defer}</small><strong>${d.deferAction}</strong></div></div><p>${d.next} · <strong>${snapshot.nextChange}</strong></p><button class="why" type="button" data-why aria-expanded="false">${d.why}</button><div class="explain" data-explain hidden><strong>${snapshot.decision} · ${safe(snapshot.sourceId)}</strong><p class="muted">${d.explain}</p></div></article><h2>${d.layers}</h2>${d.sources.map(source=>`<div class="layer"><div><strong>${safe(source[0])}</strong><div class="muted">${safe(source[1])}</div></div><div class="badge ${source[2]==='TRADITIONAL'?'traditional':''}">${source[2]}<br>${safe(source[3])}</div></div>`).join('')}`}
const dayContext=[-3,-2,-1,-1,0,-2,-1,0,1,0,-1,-2,-1,0,1,0,-1,-1,0,1,2,1,0,-1,0,1,-1];
const timelineMeta={uk:{overview:'Сирий контекст · не оперативне рішення.',color:'Колір = сирий контекст',day:'День',labels:{low:'напружено',high:'підвищено',mixed:'змішано'}},en:{overview:'Raw context overview · not an operational verdict.',color:'Color = raw context',day:'Day',labels:{low:'tense',high:'elevated',mixed:'mixed'}},es:{overview:'Contexto bruto · no es un veredicto operativo.',color:'Color = contexto bruto',day:'Día',labels:{low:'tenso',high:'elevado',mixed:'mixto'}}};
function timelineView(t){const d=t.timeline;const m=timelineMeta[locale.value];const rangeButtons=`<div class="range-switch" aria-label="Timeline range">${[['24h','24 h'],['3d','3 d'],['27d','27 d']].map(([id,label])=>`<button type="button" data-range="${id}" aria-pressed="${timelineRange===id}">${label}</button>`).join('')}</div>`;if(timelineRange==='27d')return `<h1>${d.days}</h1>${rangeButtons}<p class="muted">${m.overview}</p><div class="day-strip" role="list">${dayContext.map((value,index)=>{const state=value<=-2?'low':value>=1?'high':'mixed';const label=m.labels[state];return `<div class="day-cell ${state}" role="listitem" aria-label="${m.day} ${index+1}: ${label}, raw ${value>=0?'+':''}${value}"><small>${index+1}</small><strong>${value>=0?'+':''}${value}</strong><span>${label}</span></div>`}).join('')}</div><div class="notice"><strong>${m.color}</strong><p>${d.note}</p></div>`;const slots=timelineRange==='3d'?[...d.slots,...d.slots.map(s=>[s[0],s[1],s[2],`+1d · ${s[3]}`]),...d.slots.map(s=>[s[0],s[1],s[2],`+2d · ${s[3]}`])]:d.slots;return `<h1>${d.title}</h1>${rangeButtons}${slots.map(s=>`<div class="slot ${s[1]}"><strong>${s[0]}</strong><span class="dot" aria-hidden="true"></span><div><strong>${s[2]}</strong><div class="muted">${s[3]}</div></div></div>`).join('')}<div class="notice"><strong>${d.days}</strong><p>${d.note}</p></div>`}
function skyView(t){const d=t.sky;return `<h1>${d.title}</h1><p class="muted">${d.intro}</p><div class="sky-grid">${d.cards.map(x=>`<article class="panel"><small>${x[0]}</small><strong>${x[1]}</strong><span class="muted">${x[2]}</span></article>`).join('')}</div><div class="notice">${d.note}</div>`}
function jyotishView(t){return `<h1>Jyotish</h1><p class="muted">${t.jyotish.intro}</p>${[['Tithi','Amavasya'],['Nakshatra','Ashlesha · 4 pada'],['Vara','Budhavara'],['Yoga','Vyatipata'],['Karana','Chatushpada']].map(x=>`<div class="jyotish-row"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}<div class="notice"><strong>Rahu Kalam · 13:03–14:54</strong><p>${t.jyotish.rahunote}</p></div>`}
function youView(t){const d=t.you;return `<h1>${d.title}</h1><p class="muted">${d.intro}</p><div class="activity-grid">${Object.entries(d.choices).map(([id,label])=>`<button class="choice" data-activity="${id}" type="button" aria-pressed="${id===activity}">${label}</button>`).join('')}</div><div class="notice"><strong>12:00–13:00 · PREPARE</strong><p>CAUTION · LIVE. ${d.result}</p></div><h2>${d.after}</h2><div class="activity-grid">${d.outcomes.map((label,index)=>`<button class="choice" data-outcome="${['better','expected','mixed'][index]}" type="button">${label}</button>`).join('')}</div><p class="muted">${d.local} (${localState.checkins.length})</p><h2>Alert rules</h2><div class="alert-settings"><label><input data-alert="kp" type="checkbox" ${localState.alerts.kp?'checked':''}> Kp forecast threshold</label><label><input data-alert="decision" type="checkbox" ${localState.alerts.decision?'checked':''}> Decision-state change</label><label>Threshold Kp <input data-threshold type="number" min="4" max="9" step="1" value="${localState.alerts.threshold}"></label><div class="quiet-grid"><label>Quiet from <input data-quiet="quietStart" type="time" value="${localState.alerts.quietStart}"></label><label>to <input data-quiet="quietEnd" type="time" value="${localState.alerts.quietEnd}"></label></div></div><p class="muted">Preferences only. Push permission is not requested in this build.</p><div class="data-actions"><button class="choice" data-export type="button">${d.export}</button><button class="choice danger" data-delete type="button">${d.delete}</button></div><p class="muted">${d.birth}</p>`}
function applyChrome(t){document.documentElement.lang=locale.value;document.getElementById('mode').textContent=t.largeText;locale.setAttribute('aria-label',t.language);document.querySelectorAll('[data-route]').forEach(button=>button.textContent=t.nav[button.dataset.route]);}
function render(){const t=copy[locale.value];applyChrome(t);content.innerHTML=({today:todayView,timeline:timelineView,sky:skyView,jyotish:jyotishView,you:youView}[route])(t);content.querySelector('[data-why]')?.addEventListener('click',event=>{const drawer=content.querySelector('[data-explain]');drawer.hidden=!drawer.hidden;event.currentTarget.setAttribute('aria-expanded',String(!drawer.hidden));});content.querySelectorAll('[data-range]').forEach(button=>button.addEventListener('click',()=>{timelineRange=button.dataset.range;render();}));content.querySelectorAll('[data-activity]').forEach(button=>button.addEventListener('click',()=>{activity=button.dataset.activity;persist();render();}));content.querySelectorAll('[data-outcome]').forEach(button=>button.addEventListener('click',()=>{localState.checkins.push({activity,outcome:button.dataset.outcome,recordedAt:new Date().toISOString(),snapshot:{decision:snapshot.decision,freshness:snapshot.freshness}});persist();render();}));content.querySelectorAll('[data-alert]').forEach(input=>input.addEventListener('change',()=>{localState.alerts[input.dataset.alert]=input.checked;persist();}));const thresholdInput=content.querySelector('[data-threshold]');const saveThreshold=()=>{localState.alerts.threshold=Math.max(4,Math.min(9,Number(thresholdInput.value)||5));thresholdInput.value=localState.alerts.threshold;persist();};thresholdInput?.addEventListener('input',saveThreshold);thresholdInput?.addEventListener('change',saveThreshold);content.querySelectorAll('[data-quiet]').forEach(input=>input.addEventListener('change',()=>{localState.alerts[input.dataset.quiet]=input.value;persist();}));content.querySelector('[data-export]')?.addEventListener('click',downloadLocalData);content.querySelector('[data-delete]')?.addEventListener('click',()=>{localStorage.removeItem(storageKey);localState={locale:'uk',largeText:false,activity:'focus',checkins:[],alerts:{kp:true,decision:false,threshold:5,quietStart:'22:00',quietEnd:'07:00'}};activity='focus';locale.value='uk';document.documentElement.classList.remove('large-text');document.getElementById('mode').setAttribute('aria-pressed','false');render();});}
document.querySelectorAll('[data-route]').forEach(button=>button.addEventListener('click',()=>{route=button.dataset.route;document.querySelectorAll('[data-route]').forEach(peer=>{if(peer===button)peer.setAttribute('aria-current','page');else peer.removeAttribute('aria-current');});render();content.focus();}));
locale.addEventListener('change',()=>{persist();render();});
document.getElementById('mode').addEventListener('click',event=>{const active=document.documentElement.classList.toggle('large-text');event.currentTarget.setAttribute('aria-pressed',String(active));persist();});
render();
fetch('./mobile-snapshot.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error(`snapshot HTTP ${response.status}`);return response.json();}).then(data=>{acceptSnapshot(data);render();}).catch(()=>{snapshot={decision:'UNKNOWN',freshness:'STALE',ageMinutes:null,nextChange:'—',sourceId:'UNAVAILABLE',sourceRole:'UNAVAILABLE',research:{tanitaScoreEffect:0,v19_2ScoreEffect:0}};render();});
