import * as Astronomy from 'astronomy-engine';
const SIGNS=['Mesha','Vrishabha','Mithuna','Karka','Simha','Kanya','Tula','Vrischika','Dhanu','Makara','Kumbha','Meena'];
const NAKSHATRAS=['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishtha','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'];
const DASHA=[['Ketu',7],['Venus',20],['Sun',6],['Moon',10],['Mars',7],['Rahu',18],['Jupiter',16],['Saturn',19],['Mercury',17]], norm=x=>((x%360)+360)%360, yearDays=365.2425;
export function lahiriApprox(date){const years=(date.getTime()-Date.UTC(2000,0,1,12))/(yearDays*86400000);return 23.85675+years*(50.290966/3600);}
function tropicalLongitude(body,date){return norm(Astronomy.Ecliptic(Astronomy.GeoVector(body,date,true)).elon);}
function meanNode(date){const jd=2440587.5+date.getTime()/86400000,T=(jd-2451545)/36525;return norm(125.04452-1934.136261*T+0.0020708*T*T+(T*T*T)/450000);}
function ascendant(date,lat,lon,aya){const theta=norm(Astronomy.SiderealTime(date)*15+lon)*Math.PI/180,jd=2440587.5+date.getTime()/86400000,T=(jd-2451545)/36525,eps=(23.439291-0.0130042*T)*Math.PI/180,phi=lat*Math.PI/180;return norm(Math.atan2(-Math.cos(theta),Math.sin(eps)*Math.tan(phi)+Math.cos(eps)*Math.sin(theta))*180/Math.PI-aya+180);}
function placement(name,x){const lon=norm(x),s=Math.floor(lon/30),n=Math.floor(lon/(30/9))%12;return{name,longitude_deg:+lon.toFixed(6),sign_index:s,sign:SIGNS[s],degree_in_sign:+(lon%30).toFixed(6),d9_sign_index:n,d9_sign:SIGNS[n]};}
function vimshottari(moon,date){const span=360/27,nak=Math.floor(moon/span),f=(moon%span)/span,li=nak%9,[lord,years]=DASHA[li],elapsed=years*f,start=new Date(date.getTime()-elapsed*yearDays*86400000),periods=[];let cursor=start;for(let i=0;i<9;i++){const[name,duration]=DASHA[(li+i)%9],end=new Date(cursor.getTime()+duration*yearDays*86400000);periods.push({lord:name,start_utc:cursor.toISOString(),end_utc:end.toISOString(),years:duration});cursor=end;}return{janma_nakshatra_index:nak,janma_nakshatra:NAKSHATRAS[nak],pada:Math.floor((moon%span)/(span/4))+1,balance_at_birth:+(years*(1-f)).toFixed(6),periods};}
export function calculateJyotish(input){const date=new Date(input.datetime_utc),lat=Number(input.latitude),lon=Number(input.longitude);if(!Number.isFinite(date.getTime()))throw Error('invalid datetime_utc');if(!Number.isFinite(lat)||lat< -66||lat>66)throw Error('latitude outside validated research range [-66,66]');if(!Number.isFinite(lon)||lon< -180||lon>180)throw Error('invalid longitude');const aya=lahiriApprox(date),bodies=[['Sun',Astronomy.Body.Sun],['Moon',Astronomy.Body.Moon],['Mercury',Astronomy.Body.Mercury],['Venus',Astronomy.Body.Venus],['Mars',Astronomy.Body.Mars],['Jupiter',Astronomy.Body.Jupiter],['Saturn',Astronomy.Body.Saturn]],graha=bodies.map(([n,b])=>placement(n,tropicalLongitude(b,date)-aya)),rahu=norm(meanNode(date)-aya);graha.push(placement('Rahu',rahu),placement('Ketu',rahu+180));const lagna=placement('Lagna',ascendant(date,lat,lon,aya)),moon=graha.find(x=>x.name==='Moon');return{schema:'neborythm_jyotish_personal_research_v1',generated_at:new Date().toISOString(),input:{datetime_utc:date.toISOString(),latitude:lat,longitude:lon},engine:{name:'Astronomy Engine',version:'2.1.19',license:'MIT',ayanamsha:'LAHIRI_LINEAR_APPROX_RESEARCH',ayanamsha_deg:+aya.toFixed(6),house_system:'WHOLE_SIGN'},activation:'BLOCKED_PENDING_100_INDEPENDENT_CHARTS_AND_EDITORIAL_REVIEW',source_role:'TRADITIONAL_SHADOW',score_effect:0,d1:{lagna,graha,bhava:Array.from({length:12},(_,i)=>({house:i+1,sign_index:(lagna.sign_index+i)%12,sign:SIGNS[(lagna.sign_index+i)%12]}))},d9:{lagna_sign_index:lagna.d9_sign_index,lagna_sign:lagna.d9_sign,graha:graha.map(({name,d9_sign_index, d9_sign})=>({name,sign_index:d9_sign_index,sign:d9_sign}))},vimshottari:vimshottari(moon.longitude_deg,date),limitations:['Lahiri ayanamsha is an approximation, not Swiss Ephemeris','mean lunar node is used','high latitudes outside ±66 are rejected','no interpretation may override the operational forecast']};}
