const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');
const code=html.slice(html.indexOf('// BEGIN product render queue'),html.indexOf('// END product render queue'));
const frames=[],listeners={},calls=[],checks=[];let route='today',resolves=0,score=1,snapshot;
const c={window:{},document:{hidden:false,querySelector:()=>({dataset:{route}}),addEventListener:(n,f)=>listeners[n]=f},console,requestAnimationFrame:f=>(frames.push(f),frames.length),canonicalForDate:d=>(resolves++,{ds:d.ds,signal:{score}}),renderUnifiedForecast:()=>{calls.push('forecast');snapshot=c.operationalForDate({ds:'2026-09-29',G:1});assert.equal(c.operationalForDate({ds:'2026-09-29',G:1}),snapshot);c.requestProductRender('cover')},renderCalendar:()=>calls.push('calendar'),renderIndependentForecasts:()=>calls.push('independent'),renderCompetitiveCover:()=>{calls.push('cover');c.operationalForDate({ds:'2026-09-29',G:1})}};
vm.createContext(c);vm.runInContext(code,c);const flush=()=>{assert.equal(frames.length,1);frames.shift()()};
for(let i=0;i<20;i++)c.requestProductRender('forecast','calendar','cover','independent');flush();
assert.deepEqual(calls,['cover']);assert.equal(resolves,1);checks.push('20 events coalesce; hidden routes not rendered');
calls.length=0;route='forecast';c.requestProductRender();flush();assert.deepEqual(calls,['forecast','independent','cover']);assert.equal(resolves,2);assert(Object.isFrozen(snapshot)&&Object.isFrozen(snapshot.signal));checks.push('one immutable resolved result shared by forecast and cover within batch');
score=2;assert.equal(snapshot.signal.score,1);calls.length=0;c.requestProductRender('forecast');flush();assert.equal(snapshot.signal.score,2);checks.push('new frame recomputes changed inputs; previous snapshot cannot mutate');
calls.length=0;c.document.hidden=true;c.requestProductRender('cover');assert.equal(frames.length,0);c.document.hidden=false;listeners.visibilitychange();flush();assert.deepEqual(calls,['cover']);checks.push('hidden events remain pending until visible');
calls.length=0;route='calendar';c.requestProductRender();flush();assert.deepEqual(calls,['calendar']);checks.push('dirty calendar rendered on route activation');
calls.length=0;route='forecast';c.renderUnifiedForecast=()=>{throw Error('injected render failure')};c.requestProductRender('forecast','cover');flush();assert.deepEqual(calls,['cover']);assert.equal(c.window.__lastProductRender.errors.length,1);checks.push('one renderer failure cannot suppress other components');
(async()=>{
 let release,started=0;c.renderIndependentForecasts=()=>{started++;return new Promise(r=>release=r)};
 c.requestProductRender('independent');flush();c.requestProductRender('independent');flush();assert.equal(started,1);
 release();await new Promise(r=>setImmediate(r));flush();assert.equal(started,2);
 release();await new Promise(r=>setImmediate(r));assert.equal(frames.length,0);
 checks.push('async panel remains single-flight and retains one pending refresh');
 fs.writeFileSync(path.join(__dirname,'RENDER_QUEUE_RESULTS.json'),JSON.stringify({status:'PASS',checks},null,2));console.log('PASS',checks);
})().catch(e=>{console.error(e);process.exitCode=1});
