const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..'),frames=new Map();let serial=0,now=0,reduced=false,created=0;
const host={performance:{now:()=>now},requestAnimationFrame:f=>{frames.set(++serial,f);return serial},cancelAnimationFrame:id=>frames.delete(id),matchMedia:()=>({matches:reduced})};
const intl={DateTimeFormat:new Proxy(Intl.DateTimeFormat,{construct(t,a){created++;return new t(...a)}})};
vm.runInNewContext(fs.readFileSync(path.join(root,'presentation_runtime_v1.js'),'utf8'),{window:host,Intl:intl});
const {dateFormatter,heroValue}=host.NRPresentation,checks=[];
const options={timeZone:'Europe/Kyiv',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'};
const f=dateFormatter('en-CA',options);for(let i=0;i<1000;i++)assert.equal(dateFormatter('en-CA',{...options}),f);assert.equal(created,1);
for(const time of ['2026-03-29T00:59:59Z','2026-03-29T01:00:00Z','2026-10-25T00:59:59Z','2026-10-25T01:00:00Z','2026-09-30T20:59:59Z','2026-09-30T21:00:00Z','2026-12-31T22:00:00Z']){const d=new Date(time),reference=new Intl.DateTimeFormat('en-CA',options);assert.equal(f.format(d),reference.format(d));assert.equal(JSON.stringify(f.formatToParts(d)),JSON.stringify(reference.formatToParts(d)))}
assert.notEqual(f.format(new Date('2026-09-30T20:59:59Z')),f.format(new Date('2026-09-30T21:00:00Z')));checks.push('1000 repeated requests construct one formatter; exact dates and parts across Kyiv midnight, DST and year boundary');
for(let i=0;i<40;i++)dateFormatter('en-US',{timeZone:i%2?'UTC':'Europe/Kyiv',year:'numeric',unused:i});assert.notEqual(dateFormatter('en-CA',options),f);assert.throws(()=>dateFormatter('en-US',{timeZone:'invalid'}));assert.equal(dateFormatter('en-CA',options).format(new Date(0)),f.format(new Date(0)));checks.push('bounded cache evicts old formatter; invalid options throw without poisoning valid entries');
const node={textContent:'',style:{}};heroValue(node,2,true);assert.equal(node.textContent,'+2');assert.equal(frames.size,0);for(let i=0;i<100;i++)heroValue(node,2,true);assert.equal(frames.size,0);
function step(t){now=t;const pending=[...frames.values()];frames.clear();for(const fn of pending)fn(t)}
heroValue(node,-3,true);assert.equal(frames.size,1);const id=[...frames.keys()][0];heroValue(node,-3,true);assert.equal([...frames.keys()][0],id);step(300);heroValue(node,1,true);assert.equal(frames.size,1);step(900);assert.equal(node.textContent,'+1');assert.equal(frames.size,0);assert.equal(node.style.transform,'scale(1)');checks.push('initial/unchanged values use zero frames; active same-target sync does not restart; changed target cancels and completes once');
heroValue(node,1,false);assert.equal(node.textContent,'+1.00');assert.equal(frames.size,0);heroValue(node,-2,false);assert.equal(frames.size,1);heroValue(node,NaN,false);assert.equal(node.textContent,'…');assert.equal(frames.size,0);heroValue(node,3,false);assert.equal(node.textContent,'+3.00');reduced=true;heroValue(node,-1,false);assert.equal(node.textContent,'-1.00');assert.equal(frames.size,0);checks.push('format mode, unavailable value, recovery and reduced motion remain correct');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');assert(html.includes('src="./presentation_runtime_v1.js"'));assert(sw.includes("'./presentation_runtime_v1.js'"));assert(html.includes('window.NRPresentation.heroValue(heroG,_heroDisplayVal,_hasVerdict)'));assert(!html.includes('new Intl.DateTimeFormat('));
fs.writeFileSync(path.join(__dirname,'PRESENTATION_RESULTS.json'),JSON.stringify({status:'PASS',checks},null,2));console.log('PASS',checks);
