const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');const {chromium}=require('playwright');
const O=__dirname,root=path.resolve(O,'../..');const {resolveBrowserOptions}=require(path.join(root,'tests/audit_runtime/browser_options.cjs'));
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(f===root)f=path.join(root,'index.html');if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',f.endsWith('.html')?'text/html; charset=utf-8':f.endsWith('.js')?'application/javascript':'application/json');res.end(fs.readFileSync(f));}catch(e){res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...resolveBrowserOptions()});try{const page=await browser.newPage({serviceWorkers:'block',timezoneId:'Europe/Kyiv',viewport:{width:1400,height:1000}}),base='http://127.0.0.1:'+server.address().port;await page.route('**/*',r=>r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/?channel=play');await page.waitForFunction(()=>typeof window.fp463CanonicalForDate==='function');
await page.locator('#threeContent').evaluate(e=>{for(let p=e;p;p=p.parentElement){p.style.setProperty('display','block','important');p.style.setProperty('visibility','visible','important');p.style.opacity='1';}});
const report=await page.evaluate(payload=>{todayKyivStr=()=> '2026-09-25';const out=parse3DaySafe(payload);render3Day(out);renderDayForecast(out,0,0);return {days:out.days.map(d=>({date:fmtDate(d.date),kpMax:Number.isFinite(d.kpMax)?d.kpMax:null,slots:d.kp8.length})),slots:window._daySlots,text:document.getElementById('threeContent').textContent,html:document.getElementById('threeContent').innerHTML};},fs.readFileSync(path.join(root,'tests/audit_runtime/fixtures/noaa_forecast_20260925.json'),'utf8'));
fs.writeFileSync(path.join(O,'BROWSER_ATTEMPT.json'),JSON.stringify(report,null,2));assert.equal(report.days.length,3);assert.equal(report.days[0].kpMax,null);assert.equal(report.days[1].kpMax,3.67);assert.equal(report.slots.length,0);assert(report.text.includes('3.67'));assert(!report.text.includes('NaN'));assert(!report.text.includes('null'));
const uafRender=await page.evaluate(()=>{const x=uafTo3DayFormat({kp3Day:[],kp27Day:[{date:new Date('2026-09-25T00:00:00Z'),kp:0}]});render3Day(x);renderDayForecast(x,0,0);return {text:document.getElementById('threeContent').textContent,kp:x.days[0].kpMax,ap:x.predictedAp[0].Ap,slots:window._daySlots.length};});assert.equal(uafRender.kp,0);assert.equal(uafRender.ap,null);assert.equal(uafRender.slots,0);assert(!uafRender.text.includes('null'));assert(!uafRender.text.includes('NaN'));report.uafDaily={kp:0,ap:null,noFabricatedSlots:true,rendered:true};

const apRender=await page.evaluate(payload=>{const rows=apOnlyTo27Day(parse45Day(payload));document.getElementById('sel27Filter').value='all';render27Day(rows,null);return {rows:rows.length,text:document.getElementById('twentysevenContent').textContent,missingKp:rows.every(r=>!Number.isFinite(r.kpMax))};},fs.readFileSync(path.join(root,'tests/audit_runtime/fixtures/noaa_45day_20260925.json'),'utf8'));assert.equal(apRender.rows,45);assert(apRender.missingKp);assert(!apRender.text.includes('NaN'));assert(!apRender.text.includes('null'));report.apOnly45={rows:45,missingKp:true,rendered:true};
const preview=await browser.newPage({viewport:{width:1600,height:700}});await preview.setContent('<html><head><meta charset="utf-8"><style>body{font:14px Arial;background:#081321;color:#eee}table{border-collapse:collapse;width:100%}td,th{border:1px solid #567;padding:8px}.hint-pop,.audit-only{display:none}</style></head><body>'+report.html+'</body></html>');await preview.screenshot({path:path.join(O,'three_day_render.png'),fullPage:true});delete report.html;
fs.writeFileSync(path.join(O,'BROWSER_RESULT.json'),JSON.stringify({state:'PASS',...report},null,2));console.log('browser parser => actual renderer PASS');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
