const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..'),data=new Map(),c={window:{},Date};let denied=false,quota=false;
Object.defineProperty(c,'localStorage',{get(){if(denied)throw Error('private denied payload');return {getItem:k=>data.get(k)??null,setItem:(k,v)=>{if(quota)throw Error('private quota payload');data.set(k,String(v))},removeItem:k=>data.delete(k)}}});
vm.createContext(c);for(const file of ['runtime_diagnostics_v1.js','local_storage_v1.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),c);
const s=c.window.NRStorage,checks=[];assert(Object.isFrozen(s));assert.equal(s.get('missing'),'');assert.equal(s.get('missing',null),null);assert.equal(s.set('private key',0),undefined);assert.equal(s.get('private key'),'0');s.set('empty','');assert.equal(s.get('empty','fallback'),'');assert.equal(s.remove('private key'),undefined);assert.equal(s.get('private key','fallback'),'fallback');assert.equal(c.window.NRDiagnostics.snapshot().total,0);checks.push('missing/empty/zero values and legacy undefined write/delete returns preserved');
denied=true;assert.equal(s.get('private key','fallback'),'fallback');assert.doesNotThrow(()=>s.set('private key','private value'));assert.doesNotThrow(()=>s.remove('private key'));denied=false;quota=true;s.set('private key','private value');quota=false;s.set('recovery','ok');assert.equal(s.get('recovery'),'ok');
const snap=c.window.NRDiagnostics.snapshot();assert.equal(snap.counts['recoverable:storage.read'],1);assert.equal(snap.counts['recoverable:storage.write'],2);assert.equal(snap.counts['recoverable:storage.remove'],1);assert(!JSON.stringify(snap).includes('private'));checks.push('denied storage and quota failures are recoverable, counted without payload; next operation recovers');
const html=require('../../tools/read_runtime_source.cjs')(require('path').resolve(__dirname,'../..')),sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');for(const n of ['local_storage_v1.js','product_render_queue_v1.js']){assert(html.includes(`src="./${n}"`));assert(sw.includes(`'./${n}'`))}for(const site of ['storage.runtime_bridge','storage.snapshot_write','storage.snapshot_read'])assert(html.includes(`'${site}','recoverable'`));checks.push('modules included in offline shell; canonical snapshot and runtime bridge failures classified');
fs.writeFileSync(path.join(__dirname,'LOCAL_STORAGE_RESULTS.json'),JSON.stringify({status:'PASS',checks},null,2));console.log('PASS',checks);
